# Generated by Django 3.1.5 on 2021-03-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-votes']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted']},
        ),
        migrations.AddField(
            model_name='answer',
            name='show_identity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='show_identity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='show_identity',
            field=models.BooleanField(default=False),
        ),
    ]
